# -*- coding: utf-8 -*-
"""Kopie von MastersThesis.ipynb

Automatically generated by Colab.

# Prepare the environment

Print current working directory
"""

import os
print(os.getcwd())

"""Change the working directory to the correct one"""

# TODO: Change to the correct repository
os.chdir('/content/drive/MyDrive/Masters_Thesis/Python_MastersThesis')
print("New working directory:", os.getcwd())

"""Install required Libraries"""

!pip install -r requirements.txt

"""# Run the Models

Change the working directory to the one containing the models
"""

# TODO: Change to the correct repository
import os
os.chdir('/content/drive/MyDrive/Masters_Thesis/Python_MastersThesis/models')
print("New working directory:", os.getcwd())

!rm -rf /root/nltk_data
!rm -rf /usr/nltk_data
!rm -rf /usr/share/nltk_data
!rm -rf /usr/lib/nltk_data
!rm -rf /usr/local/share/nltk_data
!rm -rf /usr/local/lib/nltk_data

"""**Execute the SentiWordNets Model**"""

!pip install nltk==3.7 --quiet

# TODO: change the data_type variable in the model files to determine which datasets should be used for training and predicting

!python SentiWordNets.py

"""**Execute the Vader Model**"""

!python Vader.py

"""**Execute the Combined Vader and SentiWordNets Model**"""

!python Vader_SentiWordNets.py

"""**Execute the Naive Bayes Model**"""

!python NaiveBayes.py

"""**Execute the SVM Model**"""

!python SVM.py

"""**Execute the Logistic Regression Model**"""

!python LogisticRegression.py

"""**Execute the Random Forest Model**"""

!python RandomForest.py

"""**Execute the BERT Model**"""

!python BERT.py
